@FinancePlan_HostAddress = https://localhost:7097

GET {{FinancePlan_HostAddress}}/api/category

###

GET {{FinancePlan_HostAddress}}/api/expense

###

GET {{FinancePlan_HostAddress}}/api/income

###

GET {{FinancePlan_HostAddress}}/weatherforecast

###
